In [53]:
import numpy as np 
import pandas as pd

In [54]:
prices = pd.read_csv("../data/raw/train.csv")
print("Shape of prices: {}".format(prices.shape))

Shape of prices: (1460, 81)

## Exploring data

Which columns have NA values?

In [55]:
print("Which columns have NA values?")
nas = prices.isnull().any()
print(nas[nas == True])

Which columns have NA values?
LotFrontage     True
Alley           True
MasVnrType      True
MasVnrArea      True
BsmtQual        True
BsmtCond        True
BsmtExposure    True
BsmtFinType1    True
BsmtFinType2    True
Electrical      True
FireplaceQu     True
GarageType      True
GarageYrBlt     True
GarageFinish    True
GarageQual      True
GarageCond      True
PoolQC          True
Fence           True
MiscFeature     True
dtype: bool

Classification of features into Nominal/Ordinal/Quantitative has been done in /reports/Data-classification.ods

In [56]:
nominals = ['MSSubClass', 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
            'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
            'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
            'Foundation', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'CentralAir', 'Electrical',
            'Functional', 'GarageType', 'GarageFinish', 'PavedDrive', 'Fence', 'MiscFeature', 'SaleType',
            'SaleCondition']

ordinals = ['OverallQual', 'OverallCond', 'ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
           'HeatingQC', 'KitchenQual', 'FireplaceQu', 'GarageQual','GarageCond', 'PoolQC']

quant_ratio = ['YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'MoSold', 'YrSold']

quant_int = ['LotFrontage', 'LotArea', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
           'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
           'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 
           'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageCars',
           'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 
           'ScreenPorch', 'PoolArea', 'MiscVal', 'SalePrice']

In [69]:
prices.describe(include=[np.number])

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000


Let's check the nominal features to get an idea of the relative frequency of each value.

In [58]:
for nom in nominals:
    
    print(nom+" Has null values? {}\n".format(prices[nom].isnull().any()))
    print(nom+": Different classes \n{}\n".format(np.unique(prices[~prices[nom].isnull()][nom])))
    print(nom+": Occurrences per class\n{}".format(prices[nom].value_counts()))
    print("\n--------------------------------------\n")

MSSubClass Has null values? False

MSSubClass: Different classes
[ 20  30  40  45  50  60  70  75  80  85  90 120 160 180 190]

MSSubClass: Occurrences per class
20     536
60     299
50     144
120     87
30      69
160     63
70      60
80      58
90      52
190     30
85      20
75      16
45      12
180     10
40       4
Name: MSSubClass, dtype: int64

--------------------------------------

MSZoning Has null values? False

MSZoning: Different classes
['C (all)' 'FV' 'RH' 'RL' 'RM']

MSZoning: Occurrences per class
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64

--------------------------------------

Street Has null values? False

Street: Different classes
['Grvl' 'Pave']

Street: Occurrences per class
Pave    1454
Grvl       6
Name: Street, dtype: int64

--------------------------------------

Alley Has null values? True

Alley: Different classes
['Grvl' 'Pave']

Alley: Occurrences per class
Grvl    50
Pave    41
Name: Alley, dtype: int64

--------------------------------------

LotShape Has null values? False

LotShape: Different classes
['IR1' 'IR2' 'IR3' 'Reg']

LotShape: Occurrences per class
Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64

--------------------------------------

LandContour Has null values? False

LandContour: Different classes
['Bnk' 'HLS' 'Low' 'Lvl']

LandContour: Occurrences per class
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: LandContour, dtype: int64

--------------------------------------

Utilities Has null values? False

Utilities: Different classes
['AllPub' 'NoSeWa']

Utilities: Occurrences per class
AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64

--------------------------------------

LotConfig Has null values? False

LotConfig: Different classes
['Corner' 'CulDSac' 'FR2' 'FR3' 'Inside']

LotConfig: Occurrences per class
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: LotConfig, dtype: int64

--------------------------------------

LandSlope Has null values? False

LandSlope: Different classes
['Gtl' 'Mod' 'Sev']

LandSlope: Occurrences per class
Gtl    1382
Mod      65
Sev      13
Name: LandSlope, dtype: int64

--------------------------------------

Neighborhood Has null values? False

Neighborhood: Different classes
['Blmngtn' 'Blueste' 'BrDale' 'BrkSide' 'ClearCr' 'CollgCr' 'Crawfor'
 'Edwards' 'Gilbert' 'IDOTRR' 'MeadowV' 'Mitchel' 'NAmes' 'NPkVill'
 'NWAmes' 'NoRidge' 'NridgHt' 'OldTown' 'SWISU' 'Sawyer' 'SawyerW'
 'Somerst' 'StoneBr' 'Timber' 'Veenker']

Neighborhood: Occurrences per class
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64

--------------------------------------

Condition1 Has null values? False

Condition1: Different classes
['Artery' 'Feedr' 'Norm' 'PosA' 'PosN' 'RRAe' 'RRAn' 'RRNe' 'RRNn']

Condition1: Occurrences per class
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: Condition1, dtype: int64

--------------------------------------

Condition2 Has null values? False

Condition2: Different classes
['Artery' 'Feedr' 'Norm' 'PosA' 'PosN' 'RRAe' 'RRAn' 'RRNn']

Condition2: Occurrences per class
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
RRAn         1
PosA         1
RRAe         1
Name: Condition2, dtype: int64

--------------------------------------

BldgType Has null values? False

BldgType: Different classes
['1Fam' '2fmCon' 'Duplex' 'Twnhs' 'TwnhsE']

BldgType: Occurrences per class
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64

--------------------------------------

HouseStyle Has null values? False

HouseStyle: Different classes
['1.5Fin' '1.5Unf' '1Story' '2.5Fin' '2.5Unf' '2Story' 'SFoyer' 'SLvl']

HouseStyle: Occurrences per class
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64

--------------------------------------

RoofStyle Has null values? False

RoofStyle: Different classes
['Flat' 'Gable' 'Gambrel' 'Hip' 'Mansard' 'Shed']

RoofStyle: Occurrences per class
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: RoofStyle, dtype: int64

--------------------------------------

RoofMatl Has null values? False

RoofMatl: Different classes
['ClyTile' 'CompShg' 'Membran' 'Metal' 'Roll' 'Tar&Grv' 'WdShake' 'WdShngl']

RoofMatl: Occurrences per class
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
ClyTile       1
Roll          1
Name: RoofMatl, dtype: int64

--------------------------------------

Exterior1st Has null values? False

Exterior1st: Different classes
['AsbShng' 'AsphShn' 'BrkComm' 'BrkFace' 'CBlock' 'CemntBd' 'HdBoard'
 'ImStucc' 'MetalSd' 'Plywood' 'Stone' 'Stucco' 'VinylSd' 'Wd Sdng'
 'WdShing']

Exterior1st: Occurrences per class
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
Stone        2
BrkComm      2
ImStucc      1
AsphShn      1
CBlock       1
Name: Exterior1st, dtype: int64

--------------------------------------

Exterior2nd Has null values? False

Exterior2nd: Different classes
['AsbShng' 'AsphShn' 'Brk Cmn' 'BrkFace' 'CBlock' 'CmentBd' 'HdBoard'
 'ImStucc' 'MetalSd' 'Other' 'Plywood' 'Stone' 'Stucco' 'VinylSd' 'Wd Sdng'
 'Wd Shng']

Exterior2nd: Occurrences per class
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
CBlock       1
Other        1
Name: Exterior2nd, dtype: int64

--------------------------------------

MasVnrType Has null values? True

MasVnrType: Different classes
['BrkCmn' 'BrkFace' 'None' 'Stone']

MasVnrType: Occurrences per class
None       864
BrkFace    445
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64

--------------------------------------

Foundation Has null values? False

Foundation: Different classes
['BrkTil' 'CBlock' 'PConc' 'Slab' 'Stone' 'Wood']

Foundation: Occurrences per class
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: Foundation, dtype: int64

--------------------------------------

BsmtFinType1 Has null values? True

BsmtFinType1: Different classes
['ALQ' 'BLQ' 'GLQ' 'LwQ' 'Rec' 'Unf']

BsmtFinType1: Occurrences per class
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: BsmtFinType1, dtype: int64

--------------------------------------

BsmtFinType2 Has null values? True

BsmtFinType2: Different classes
['ALQ' 'BLQ' 'GLQ' 'LwQ' 'Rec' 'Unf']

BsmtFinType2: Occurrences per class
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: BsmtFinType2, dtype: int64

--------------------------------------

Heating Has null values? False

Heating: Different classes
['Floor' 'GasA' 'GasW' 'Grav' 'OthW' 'Wall']

Heating: Occurrences per class
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: Heating, dtype: int64

--------------------------------------

CentralAir Has null values? False

CentralAir: Different classes
['N' 'Y']

CentralAir: Occurrences per class
Y    1365
N      95
Name: CentralAir, dtype: int64

--------------------------------------

Electrical Has null values? True

Electrical: Different classes
['FuseA' 'FuseF' 'FuseP' 'Mix' 'SBrkr']

Electrical: Occurrences per class
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

--------------------------------------

Functional Has null values? False

Functional: Different classes
['Maj1' 'Maj2' 'Min1' 'Min2' 'Mod' 'Sev' 'Typ']

Functional: Occurrences per class
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: Functional, dtype: int64

--------------------------------------

GarageType Has null values? True

GarageType: Different classes
['2Types' 'Attchd' 'Basment' 'BuiltIn' 'CarPort' 'Detchd']

GarageType: Occurrences per class
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64

--------------------------------------

GarageFinish Has null values? True

GarageFinish: Different classes
['Fin' 'RFn' 'Unf']

GarageFinish: Occurrences per class
Unf    605
RFn    422
Fin    352
Name: GarageFinish, dtype: int64

--------------------------------------

PavedDrive Has null values? False

PavedDrive: Different classes
['N' 'P' 'Y']

PavedDrive: Occurrences per class
Y    1340
N      90
P      30
Name: PavedDrive, dtype: int64

--------------------------------------

Fence Has null values? True

Fence: Different classes
['GdPrv' 'GdWo' 'MnPrv' 'MnWw']

Fence: Occurrences per class
MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: Fence, dtype: int64

--------------------------------------

MiscFeature Has null values? True

MiscFeature: Different classes
['Gar2' 'Othr' 'Shed' 'TenC']

MiscFeature: Occurrences per class
Shed    49
Gar2     2
Othr     2
TenC     1
Name: MiscFeature, dtype: int64

--------------------------------------

SaleType Has null values? False

SaleType: Different classes
['COD' 'CWD' 'Con' 'ConLD' 'ConLI' 'ConLw' 'New' 'Oth' 'WD']

SaleType: Occurrences per class
WD       1267
New       122
COD        43
ConLD       9
ConLw       5
ConLI       5
CWD         4
Oth         3
Con         2
Name: SaleType, dtype: int64

--------------------------------------

SaleCondition Has null values? False

SaleCondition: Different classes
['Abnorml' 'AdjLand' 'Alloca' 'Family' 'Normal' 'Partial']

SaleCondition: Occurrences per class
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: SaleCondition, dtype: int64

--------------------------------------

We see that for most features one or two values occur significantly more often than others.  

Next let's do the same check for the ordinal features.

In [59]:
for nom in ordinals:
    
    print(nom+" Has null values? {}\n".format(prices[nom].isnull().any()))
    print(nom+": Different classes \n{}\n".format(np.unique(prices[~prices[nom].isnull()][nom])))
    print(nom+": Occurrences per class\n{}".format(prices[nom].value_counts()))
    print("\n--------------------------------------\n")

OverallQual Has null values? False

OverallQual: Different classes
[ 1  2  3  4  5  6  7  8  9 10]

OverallQual: Occurrences per class
5     397
6     374
7     319
8     168
4     116
9      43
3      20
10     18
2       3
1       2
Name: OverallQual, dtype: int64

--------------------------------------

OverallCond Has null values? False

OverallCond: Different classes
[1 2 3 4 5 6 7 8 9]

OverallCond: Occurrences per class
5    821
6    252
7    205
8     72
4     57
3     25
9     22
2      5
1      1
Name: OverallCond, dtype: int64

--------------------------------------

ExterQual Has null values? False

ExterQual: Different classes
['Ex' 'Fa' 'Gd' 'TA']

ExterQual: Occurrences per class
TA    906
Gd    488
Ex     52
Fa     14
Name: ExterQual, dtype: int64

--------------------------------------

ExterCond Has null values? False

ExterCond: Different classes
['Ex' 'Fa' 'Gd' 'Po' 'TA']

ExterCond: Occurrences per class
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: ExterCond, dtype: int64

--------------------------------------

BsmtQual Has null values? True

BsmtQual: Different classes
['Ex' 'Fa' 'Gd' 'TA']

BsmtQual: Occurrences per class
TA    649
Gd    618
Ex    121
Fa     35
Name: BsmtQual, dtype: int64

--------------------------------------

BsmtCond Has null values? True

BsmtCond: Different classes
['Fa' 'Gd' 'Po' 'TA']

BsmtCond: Occurrences per class
TA    1311
Gd      65
Fa      45
Po       2
Name: BsmtCond, dtype: int64

--------------------------------------

BsmtExposure Has null values? True

BsmtExposure: Different classes
['Av' 'Gd' 'Mn' 'No']

BsmtExposure: Occurrences per class
No    953
Av    221
Gd    134
Mn    114
Name: BsmtExposure, dtype: int64

--------------------------------------

HeatingQC Has null values? False

HeatingQC: Different classes
['Ex' 'Fa' 'Gd' 'Po' 'TA']

HeatingQC: Occurrences per class
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: HeatingQC, dtype: int64

--------------------------------------

KitchenQual Has null values? False

KitchenQual: Different classes
['Ex' 'Fa' 'Gd' 'TA']

KitchenQual: Occurrences per class
TA    735
Gd    586
Ex    100
Fa     39
Name: KitchenQual, dtype: int64

--------------------------------------

FireplaceQu Has null values? True

FireplaceQu: Different classes
['Ex' 'Fa' 'Gd' 'Po' 'TA']

FireplaceQu: Occurrences per class
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: FireplaceQu, dtype: int64

--------------------------------------

GarageQual Has null values? True

GarageQual: Different classes
['Ex' 'Fa' 'Gd' 'Po' 'TA']

GarageQual: Occurrences per class
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: GarageQual, dtype: int64

--------------------------------------

GarageCond Has null values? True

GarageCond: Different classes
['Ex' 'Fa' 'Gd' 'Po' 'TA']

GarageCond: Occurrences per class
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: GarageCond, dtype: int64

--------------------------------------

PoolQC Has null values? True

PoolQC: Different classes
['Ex' 'Fa' 'Gd']

PoolQC: Occurrences per class
Gd    3
Fa    2
Ex    2
Name: PoolQC, dtype: int64

--------------------------------------

While the features OverallQual and OverallCond have numeric values, the other ordinal features have string values. The set of string values is almost the same over the ordinal features. Those values can be uniformized and then transformed into numeric values to allow an ordering between them.

## Sanity checking data

Check for duplicates and partial duplicates.

In [60]:
dups = prices.duplicated()
print(dups[dups == True])

Series([], dtype: bool)

No duplicate rows in the dataset

In [61]:
# which columns could help most to identify partial duplicates?
# Neighborhood - duplicates should be in the same neighborhood
# MoSold / YrSold - sold at the same time
# YearBuilt - the year it was built
# SalePrice - sold for the same price

dupsgrouped = prices[prices.duplicated(['Neighborhood', 'YrSold', 'MoSold', 'YearBuilt', 'SalePrice'], keep=False)].groupby(
    ['Neighborhood', 'YrSold', 'MoSold', 'YearBuilt', 'SalePrice'])
for name, dup in dupsgrouped:
    for col in dup:
        print(col)
        print(dup[col][:])
        print('\n')
    print('------------')

Id
145      146
1304    1305
Name: Id, dtype: int64


MSSubClass
145     160
1304    160
Name: MSSubClass, dtype: int64


MSZoning
145     RM
1304    RM
Name: MSZoning, dtype: object


LotFrontage
145     24.0
1304    32.0
Name: LotFrontage, dtype: float64


LotArea
145     2522
1304    3363
Name: LotArea, dtype: int64


Street
145     Pave
1304    Pave
Name: Street, dtype: object


Alley
145     NaN
1304    NaN
Name: Alley, dtype: object


LotShape
145     Reg
1304    Reg
Name: LotShape, dtype: object


LandContour
145     Lvl
1304    Lvl
Name: LandContour, dtype: object


Utilities
145     AllPub
1304    AllPub
Name: Utilities, dtype: object


LotConfig
145     Inside
1304    Inside
Name: LotConfig, dtype: object


LandSlope
145     Gtl
1304    Gtl
Name: LandSlope, dtype: object


Neighborhood
145     Edwards
1304    Edwards
Name: Neighborhood, dtype: object


Condition1
145     Norm
1304    Norm
Name: Condition1, dtype: object


Condition2
145     Norm
1304    Norm
Name: Condition2, dtype: object


BldgType
145      Twnhs
1304    TwnhsE
Name: BldgType, dtype: object


HouseStyle
145     2Story
1304    2Story
Name: HouseStyle, dtype: object


OverallQual
145     6
1304    7
Name: OverallQual, dtype: int64


OverallCond
145     5
1304    5
Name: OverallCond, dtype: int64


YearBuilt
145     2004
1304    2004
Name: YearBuilt, dtype: int64


YearRemodAdd
145     2006
1304    2004
Name: YearRemodAdd, dtype: int64


RoofStyle
145     Gable
1304    Gable
Name: RoofStyle, dtype: object


RoofMatl
145     CompShg
1304    CompShg
Name: RoofMatl, dtype: object


Exterior1st
145     VinylSd
1304    VinylSd
Name: Exterior1st, dtype: object


Exterior2nd
145     VinylSd
1304    VinylSd
Name: Exterior2nd, dtype: object


MasVnrType
145     Stone
1304    Stone
Name: MasVnrType, dtype: object


MasVnrArea
145      50.0
1304    117.0
Name: MasVnrArea, dtype: float64


ExterQual
145     Gd
1304    Gd
Name: ExterQual, dtype: object


ExterCond
145     TA
1304    TA
Name: ExterCond, dtype: object


Foundation
145     PConc
1304    PConc
Name: Foundation, dtype: object


BsmtQual
145     Gd
1304    Gd
Name: BsmtQual, dtype: object


BsmtCond
145     TA
1304    TA
Name: BsmtCond, dtype: object


BsmtExposure
145     No
1304    No
Name: BsmtExposure, dtype: object


BsmtFinType1
145     Unf
1304    Unf
Name: BsmtFinType1, dtype: object


BsmtFinSF1
145     0
1304    0
Name: BsmtFinSF1, dtype: int64


BsmtFinType2
145     Unf
1304    Unf
Name: BsmtFinType2, dtype: object


BsmtFinSF2
145     0
1304    0
Name: BsmtFinSF2, dtype: int64


BsmtUnfSF
145     970
1304    976
Name: BsmtUnfSF, dtype: int64


TotalBsmtSF
145     970
1304    976
Name: TotalBsmtSF, dtype: int64


Heating
145     GasA
1304    GasA
Name: Heating, dtype: object


HeatingQC
145     Ex
1304    Ex
Name: HeatingQC, dtype: object


CentralAir
145     Y
1304    Y
Name: CentralAir, dtype: object


Electrical
145     SBrkr
1304    SBrkr
Name: Electrical, dtype: object


1stFlrSF
145     970
1304    976
Name: 1stFlrSF, dtype: int64


2ndFlrSF
145     739
1304    732
Name: 2ndFlrSF, dtype: int64


LowQualFinSF
145     0
1304    0
Name: LowQualFinSF, dtype: int64


GrLivArea
145     1709
1304    1708
Name: GrLivArea, dtype: int64


BsmtFullBath
145     0
1304    0
Name: BsmtFullBath, dtype: int64


BsmtHalfBath
145     0
1304    0
Name: BsmtHalfBath, dtype: int64


FullBath
145     2
1304    2
Name: FullBath, dtype: int64


HalfBath
145     0
1304    0
Name: HalfBath, dtype: int64


BedroomAbvGr
145     3
1304    3
Name: BedroomAbvGr, dtype: int64


KitchenAbvGr
145     1
1304    1
Name: KitchenAbvGr, dtype: int64


KitchenQual
145     Gd
1304    Gd
Name: KitchenQual, dtype: object


TotRmsAbvGrd
145     7
1304    7
Name: TotRmsAbvGrd, dtype: int64


Functional
145     Maj1
1304    Maj1
Name: Functional, dtype: object


Fireplaces
145     0
1304    0
Name: Fireplaces, dtype: int64


FireplaceQu
145     NaN
1304    NaN
Name: FireplaceQu, dtype: object


GarageType
145     Detchd
1304    Detchd
Name: GarageType, dtype: object


GarageYrBlt
145     2004.0
1304    2004.0
Name: GarageYrBlt, dtype: float64


GarageFinish
145     Unf
1304    Unf
Name: GarageFinish, dtype: object


GarageCars
145     2
1304    2
Name: GarageCars, dtype: int64


GarageArea
145     380
1304    380
Name: GarageArea, dtype: int64


GarageQual
145     TA
1304    TA
Name: GarageQual, dtype: object


GarageCond
145     TA
1304    TA
Name: GarageCond, dtype: object


PavedDrive
145     Y
1304    Y
Name: PavedDrive, dtype: object


WoodDeckSF
145     0
1304    0
Name: WoodDeckSF, dtype: int64


OpenPorchSF
145     40
1304    40
Name: OpenPorchSF, dtype: int64


EnclosedPorch
145     0
1304    0
Name: EnclosedPorch, dtype: int64


3SsnPorch
145     0
1304    0
Name: 3SsnPorch, dtype: int64


ScreenPorch
145     0
1304    0
Name: ScreenPorch, dtype: int64


PoolArea
145     0
1304    0
Name: PoolArea, dtype: int64


PoolQC
145     NaN
1304    NaN
Name: PoolQC, dtype: object


Fence
145     NaN
1304    NaN
Name: Fence, dtype: object


MiscFeature
145     NaN
1304    NaN
Name: MiscFeature, dtype: object


MiscVal
145     0
1304    0
Name: MiscVal, dtype: int64


MoSold
145     4
1304    4
Name: MoSold, dtype: int64


YrSold
145     2006
1304    2006
Name: YrSold, dtype: int64


SaleType
145     WD
1304    WD
Name: SaleType, dtype: object


SaleCondition
145     Normal
1304    Normal
Name: SaleCondition, dtype: object


SalePrice
145     130000
1304    130000
Name: SalePrice, dtype: int64


------------

Only potential candidates for partial duplicate are row 145 (Id 146) and 1304 (Id 1305) - they are however sufficiently different on the LotArea to consider we are dealing with two different house sales.

The total basement surface should correspond to the sum of BsmtFin1SF, BsmtFin2SF and BsmtUnfSF. Is this true for all records?

In [62]:
#TotalBsmtSF = BsmtFin1SF + BsmtFin2SF + BsmtUnfSF -YES
bools = prices['TotalBsmtSF'] == prices['BsmtFinSF1'] + prices['BsmtFinSF2'] + prices['BsmtUnfSF']
prices[~bools.values]

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

No records found where this isn't verified.
To reduce the number of variables we can add BmsFinSF1 and BsmtFinSF2 to obtain the total BsmtFinSF and eliminate TotalBsmtSF, BsmtFinSF1 and BsmtFinSF2.

Now check the different values of the quantitative ratio features. Those features describe a year or a month.

In [63]:
for nom in quant_ratio:
    
    print(nom+" Has null values? {}\n".format(prices[nom].isnull().any()))
    print(nom+": Different classes \n{}\n".format(np.unique(prices[~prices[nom].isnull()][nom])))
    print(nom+": Occurrences per class\n{}".format(prices[nom].value_counts()))
    print("\n--------------------------------------\n")

YearBuilt Has null values? False

YearBuilt: Different classes
[1872 1875 1880 1882 1885 1890 1892 1893 1898 1900 1904 1905 1906 1908 1910
 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925
 1926 1927 1928 1929 1930 1931 1932 1934 1935 1936 1937 1938 1939 1940 1941
 1942 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958
 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973
 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988
 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003
 2004 2005 2006 2007 2008 2009 2010]

YearBuilt: Occurrences per class
2006    67
2005    64
2004    54
2007    49
2003    45
1976    33
1977    32
1920    30
1959    26
1999    25
1998    25
1958    24
1965    24
1970    24
1954    24
2000    24
2002    23
2008    23
1972    23
1968    22
1971    22
1950    20
2001    20
1957    20
1962    19
1994    19
1966    18
2009    18
1995    18
1940    18
        ..
1986     5
1952     5
1880     4
1929     4
1932     4
1938     4
1983     4
1927     3
1919     3
1934     3
1989     3
1987     3
1912     3
1885     2
1892     2
1890     2
1942     2
1908     2
1882     1
1875     1
1893     1
2010     1
1898     1
1904     1
1905     1
1906     1
1911     1
1913     1
1917     1
1872     1
Name: YearBuilt, Length: 112, dtype: int64

--------------------------------------

YearRemodAdd Has null values? False

YearRemodAdd: Different classes
[1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964
 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979
 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994
 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009
 2010]

YearRemodAdd: Occurrences per class
1950    178
2006     97
2007     76
2005     73
2004     62
2000     55
2003     51
2002     48
2008     40
1996     36
1998     36
1995     31
1976     30
1999     30
1970     26
1997     25
1977     25
2009     23
1994     22
2001     21
1972     20
1965     19
1993     19
1971     18
1959     18
1968     17
1992     17
1978     16
1966     15
1958     15
       ...
1962     14
1954     14
1969     14
1991     14
1963     13
1960     12
1967     12
1980     12
1973     11
1964     11
1989     11
1987     10
1975     10
1979     10
1956     10
1953     10
1957      9
1988      9
1955      9
1985      9
1961      8
1981      8
1974      7
1982      7
1984      7
2010      6
1983      5
1952      5
1986      5
1951      4
Name: YearRemodAdd, Length: 61, dtype: int64

--------------------------------------

GarageYrBlt Has null values? True

GarageYrBlt: Different classes
[ 1900.  1906.  1908.  1910.  1914.  1915.  1916.  1918.  1920.  1921.
  1922.  1923.  1924.  1925.  1926.  1927.  1928.  1929.  1930.  1931.
  1932.  1933.  1934.  1935.  1936.  1937.  1938.  1939.  1940.  1941.
  1942.  1945.  1946.  1947.  1948.  1949.  1950.  1951.  1952.  1953.
  1954.  1955.  1956.  1957.  1958.  1959.  1960.  1961.  1962.  1963.
  1964.  1965.  1966.  1967.  1968.  1969.  1970.  1971.  1972.  1973.
  1974.  1975.  1976.  1977.  1978.  1979.  1980.  1981.  1982.  1983.
  1984.  1985.  1986.  1987.  1988.  1989.  1990.  1991.  1992.  1993.
  1994.  1995.  1996.  1997.  1998.  1999.  2000.  2001.  2002.  2003.
  2004.  2005.  2006.  2007.  2008.  2009.  2010.]

GarageYrBlt: Occurrences per class
2005.0    65
2006.0    59
2004.0    53
2003.0    50
2007.0    49
1977.0    35
1998.0    31
1999.0    30
2008.0    29
1976.0    29
2000.0    27
2002.0    26
1968.0    26
1950.0    24
1993.0    22
2009.0    21
1965.0    21
1966.0    21
1962.0    21
1958.0    21
2001.0    20
1996.0    20
1957.0    20
1970.0    20
1960.0    19
1997.0    19
1978.0    19
1954.0    19
1974.0    18
1994.0    18
          ..
1922.0     5
1936.0     5
1916.0     5
1931.0     4
1945.0     4
1935.0     4
1928.0     4
1946.0     4
1982.0     4
1938.0     3
1921.0     3
1924.0     3
1910.0     3
1952.0     3
1932.0     3
2010.0     3
1923.0     3
1937.0     2
1934.0     2
1918.0     2
1947.0     2
1929.0     2
1914.0     2
1915.0     2
1942.0     2
1908.0     1
1927.0     1
1933.0     1
1900.0     1
1906.0     1
Name: GarageYrBlt, Length: 97, dtype: int64

--------------------------------------

MoSold Has null values? False

MoSold: Different classes
[ 1  2  3  4  5  6  7  8  9 10 11 12]

MoSold: Occurrences per class
6     253
7     234
5     204
4     141
8     122
3     106
10     89
11     79
9      63
12     59
1      58
2      52
Name: MoSold, dtype: int64

--------------------------------------

YrSold Has null values? False

YrSold: Different classes
[2006 2007 2008 2009 2010]

YrSold: Occurrences per class
2009    338
2007    329
2006    314
2008    304
2010    175
Name: YrSold, dtype: int64

--------------------------------------

The values to describe years and months seem correct (months range from 1 - 12, years from 1872 - 2010)

One would assume that some basic constraints should hold:  
- the house is built before it is sold (YearBuilt < YrSold)
- the house is built before it is remodelled (YearBuilt < YearRemodAdd)
- the house is built before or in the same year the garage is built

In [64]:
bools = prices['YearBuilt'] <= prices['YrSold']
print(prices[~bools][['YearBuilt','YrSold']])

bools = prices['YearBuilt'] <= prices['YearRemodAdd'].fillna(3000)
print(prices[~bools][['YearBuilt','YearRemodAdd']])

bools = prices['YearBuilt'] <= prices['GarageYrBlt'].fillna(3000)
print(prices[~bools][['YearBuilt','GarageYrBlt']])

Empty DataFrame
Columns: [YearBuilt, YrSold]
Index: []
Empty DataFrame
Columns: [YearBuilt, YearRemodAdd]
Index: []
      YearBuilt  GarageYrBlt
29         1927       1920.0
93         1910       1900.0
324        1967       1961.0
600        2005       2003.0
736        1950       1949.0
1103       1959       1954.0
1376       1930       1925.0
1414       1923       1922.0
1418       1963       1962.0

The first two constraints hold, however there are 9 cases where the garage was built earlier than the house.

In [65]:
nogarage = len(prices[prices['GarageYrBlt'].isnull()])
sameyear = len(prices[prices['YearBuilt'] == prices['GarageYrBlt'].fillna(3000)])
later = len(prices[prices['YearBuilt'] < prices['GarageYrBlt'].fillna(prices['YearBuilt'])])                
earlier = len(prices[prices['YearBuilt'] > prices['GarageYrBlt'].fillna(prices['YearBuilt'])])
               
print("Garage was never built : {}".format(nogarage))
print("Gargae was built same year as house : {}".format(sameyear))
print("Gargae was built later than house : {}".format(later))
print("Gargae was built earlier than house : {}".format(earlier))

Garage was never built : 81
Gargae was built same year as house : 1089
Gargae was built later than house : 281
Gargae was built earlier than house : 9

We see that for the houses that have a garage (which is the majority) the garage was built the same year as the house for 79%. It seems unusual to have a garage built earlier than the house, those 9 records should be corrected and the value of GarageYrBlt should be defaulted to YearBuilt.